### PR TITLE
#8: main layout structure (closes #8)

### LINKED ISSUE #8: main layout structure
<- #7 
## requirements

The scope of this issue is to simply define the layout. No logic, style nor sub-components (like `SearchBar` or `ResultsPanel` should be implemented)
- page should not scroll vertically (the scroll will be inside the `ResultsPanel` itself)
- main content (future `ResultsPanel` will be inside it) is centered horizontally
- main content should grow horizontally, but no higher than `1000 px`
- main content should grow vertically (we want it to fill the available vertical space)

for the mockup refer to #7 
## specs
- use `FlexView` for basic layout (https://github.com/buildo/react-components/tree/master/src/flex)
- consider using `NavBar` (https://github.com/buildo/react-components/tree/master/src/nav-bar)

### PR DESCRIPTION
**Pull request by nerder**
Issue #8 
## Test Plan
- Edit HTML and add to the second `<div>` of the list a margin-top of 1000px, you will see a vertical scroll bar.
- Edit HTML and add to the second `<div>` of the list a margin-left of 1100px (or anything >= 1001px) you will see the element disappear but no horizontal scroll bar.
- Resize the window to be less than 1000px of width you will see the results `<div>` without any borders

### CODE REVIEW

**Comment by giogonzo** [comment]
here are some comments:
- I added a commit that should make assets imports cleaner
- there's no test plan above (I know I'm being pedantic :P but see last point below)
- It looks to me that the `className`s you added on various `FlexView`s of the layout are not needed (at least not now). If I'm right, they should be removed
  Also, probably the inline style there (`components/App.js`) could go in a separate `.scss` file right next to the component. But we can do this later in another PR :)
- if I understood requirements in #8  correctly , the main content (grey area) should make its content scroll but always be 100% in height:

> page should not scroll vertically (the scroll will be inside the ResultsPanel itself)

This doesn't happen now:
[https://gyazo.com/088bf373afd566c95ac10f1c4a242de3](https://gyazo.com/088bf373afd566c95ac10f1c4a242de3)

If you had spent some time describing a test plan as complete as possible wrt requirements, you'd have spot this easily ;)

**Comment by nerder** [comment]
@giogonzo
About the test plan, you are perfectly right, i thought that "layout" features doesn't need a test plans cause they could be straight forward to check, but you show me exactly why are they important even in this case. i'll do my best to make tests that cover multiple use cases. :)  

I'm a bit confused about this two points cause they seems conflicting to me:

> It looks to me that the classNames you added on various FlexViews of the layout are not needed (at least not now). If I'm right, they should be removed

And

> Also, probably the inline style there (`components/App.js`) could go in a separate `.scss` file right next to the component.

How can i remove classNames and style it in separate `.scss` file for a specific FlexView, for instance which one that contains results? If i move the style into a new file, i have to hook the FlexView i want to style in some way. But maybe i'm missing something.

I'm going to add a test plan and add a `overflow:scroll` property to the results FlexView in order to fit the requirements.

**Comment by giogonzo** [comment]
Great :+1:

About the confusing part, our convention is more or less: use 1 single
.scss file per component. The top level class in the component (wrapper
element) should be named "my-component" for the generic "MyComponent" js
file (so e.g "app.scss" for "App.js").
Internal classes can be named what you wish but they must live inside the
top level one in the scss file

Hope this helps, also read through the convention files I sent you

**Comment by giogonzo** [comment]
:+1:

**Pull request merged**
